# NOTE: Using feed forward JointGroup{modality}Controllers as much as possible

panda_joint_effort_controller:
  type: effort_controllers/JointGroupEffortController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

panda_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

panda_joint_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7

